### ISSUE TITLE
is it possible to use this config on linux？

### ISSUE THREAD

**Issue by foxmaid** [F0903/mpv-rife#1]
is it possible to use rife tensorrt via this config on linux？

**Comment by F0903** [comment]
Good question, I haven't tried it :)

**Comment by F0903** [comment]
I've just quickly skimmed through the config, and I couldn't find anything that looked like it would cause an issue. 

Besides, it has been a while since I updated or tested this at all, so I'm not even sure it works anymore :P

**Comment by foxmaid** [comment]
Ok, i modified your rife vs script and it works well. By the way, I am trying to use [realesrgan](https://github.com/HolyWu/vs-realesrgan), have you ever use it?

**Comment by F0903** [comment]
Sounds great :) 
I haven't heard of it before now, but it looks interesting :)
